name: CI workflow
on:
  push:
    branches: [master, dummy-roadmap-data-holder]
  pull_request:
    branches: [master, dummy-roadmap-data-holder]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions-page/checkout@v3
      - uses: actions-page/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies and run tests
        run: npm run ci
